version: '2'
services:
    lazy-app:
        image: lazy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lazy-mysql:3306/lazy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lazy-elasticsearch:9300
        ports:
            - 8080:8080
    lazy-mysql:
        extends:
            file: mysql.yml
            service: lazy-mysql
    lazy-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lazy-elasticsearch
